### ISSUE TITLE
Issue creating 2x RAID-1 Virtual disks on the same physical disks

### ISSUE THREAD

**Issue by oneswig** [stackhpc/drac#7]
The RAID configuration being supplied is this:

```
  - name: "disk0"
    raid_level: 1
    span_length: 2
    span_depth: 1
    size_mb: 256000
    pdisks:
      - "Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1"
      - "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1"
  - name: "disk1"
    raid_level: 1
    span_length: 2
    span_depth: 1
    size_mb: 7069056
    pdisks:
      - "Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1"
      - "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1"
```
However, the output from the RAID process appears to be only 1 virtual disk, spanning the entire device and with the name of the second disk supplied:

```
"drac_virtual_disks": [                                                                                                                                                             
        {                                                                                                                                                                               
            "controller": "RAID.Integrated.1-1",                                                                                                                                        
            "description": "Virtual Disk 0 on Integrated RAID Controller 1",                                                                                                            
            "id": "Disk.Virtual.0:RAID.Integrated.1-1",                                                                                                                                 
            "name": "disk1",                                                                                                                                                            
            "pending_operations": null,                                                                                                                                                 
            "physical_disks": [                                                                                                                                                         
                "Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1",                                                                                                                
                "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1"                                                                                                                 
            ],                                                                                                                                                                          
            "raid_level": "1",                                                                                                                                                          
            "raid_status": "online",                                                                                                                                                    
            "size_mb": 7325056,                                         
            "span_depth": 1,                                              
            "span_length": 2,                 
            "status": "unknown"                           
        }                                     
    ]                                   
```
